name: Build & Push Docker Images to Docker Hub

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, app]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker buildx build -f backend.dockerfile -t ${{ secrets.DOCKER_USERNAME }}/planai-backend:latest . --push

      - name: Build and Push Frontend Image
        run: |
          docker buildx build -f app.dockerfile -t ${{ secrets.DOCKER_USERNAME }}/planai-frontend:latest . --push

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: SSH to EC2 and Pull & Run Docker Images
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd app
            docker-compose -f docker-compose.yaml down
            docker rmi ${{ secrets.DOCKER_USERNAME }}/planai-backend:latest
            docker rmi ${{ secrets.DOCKER_USERNAME }}/planai-frontend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/planai-backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/planai-frontend:latest
            docker-compose -f docker-compose.yaml up -d